name: Build Godot PKGBUILD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm base-devel git \
            alsa-lib mold nuget scons setconf yasm \
            brotli ca-certificates embree freetype2 graphite libglvnd \
            libspeechd libsquish libtheora libvorbis libwebp libwslay \
            libxcursor libxi libxinerama libxrandr miniupnpc openxr pcre2 \
            pulse-native-provider

      - name: Add build user
        run: |
          useradd -m builder
          chown -R builder:builder $GITHUB_WORKSPACE
          
      - name: Install 32-bit dependencies
        run: |
          sudo sed -i '/#\[multilib\]/,/Include/s/^#//' /etc/pacman.conf
          sudo pacman -Syu --noconfirm
          sudo pacman -S --needed --noconfirm \
            lib32-brotli lib32-ca-certificates lib32-freetype2 lib32-graphite \
            lib32-libglvnd lib32-libsquish lib32-libtheora lib32-libvorbis \
            lib32-libwebp lib32-libwslay lib32-libxcursor lib32-libxi \
            lib32-libxinerama lib32-libxrandr lib32-miniupnpc lib32-openxr \
            lib32-pcre2 lib32-libspeechd lib32-pipewire-alsa lib32-pulse-native-provider \
            gcc-multilib alsa-lib mold nuget scons setconf yasm



      - name: Build package
        run: |
          sudo -u builder bash -c "cd $GITHUB_WORKSPACE && makepkg -s --noconfirm"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: godot-pkg
          path: "*.pkg.tar.zst"
