name: Build Godot PKGBUILD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm base-devel git \
            alsa-lib mold nuget scons setconf yasm \
            brotli ca-certificates embree freetype2 graphite libglvnd \
            libspeechd libsquish libtheora libvorbis libwebp libwslay \
            libxcursor libxi libxinerama libxrandr miniupnpc openxr pcre2 \
            pulse-native-provider

      - name: Add build user
        run: |
          useradd -m builder
          chown -R builder:builder $GITHUB_WORKSPACE

      - name: Build package
        run: |
          sudo -u builder bash -c "cd $GITHUB_WORKSPACE && makepkg -s --noconfirm"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: godot-pkg
          path: "*.pkg.tar.zst"
