name: Build Godot PKGBUILD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest   # 👈 This makes all steps run inside Arch

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm base-devel clang llvm mold scons git sudo

          # Create builder user
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown -R builder:builder $GITHUB_WORKSPACE

      - name: Build package
        run: |
          su builder -c "cd $GITHUB_WORKSPACE && makepkg -s --noconfirm"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: godot-pkg
          path: "*.pkg.tar.zst"
