name: Build Godot PKGBUILD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install base-devel and deps
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm --needed base-devel sudo git

      - name: Create build user
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown -R builder:builder $GITHUB_WORKSPACE

      - name: Build package
        run: |
          sudo -u builder bash -c "cd $GITHUB_WORKSPACE && makepkg -s --noconfirm"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: godot-pkg
          path: ${{ github.workspace }}/*.pkg.tar.zst
