name: Build Godot PKGBUILD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm base-devel clang llvm mold scons git sudo

      - name: Build Godot package
        run: |
          cd $GITHUB_WORKSPACE
          makepkg -s --noconfirm

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: godot-pkg
          path: $GITHUB_WORKSPACE/*.pkg.tar.zst
